### ISSUE TITLE
tfsec tab freezes on "Waiting for build to complete..."

### ISSUE THREAD

**Issue by vanmash** [aquasecurity/tfsec-azure-pipelines-task#17]
I have a pipeline containing two stages: `plan` and `apply`.
`tfsec` task completes and generates reports, but tab freezes with 
`"Waiting for build to complete..."`
 message until the whole pipeline is finished. The second stage waits for manual approval.

When the second stage is skipped (in case of no changes in the plan) the tab shows an error
`Timeline record missing: cannot load results. Is tfsec configured to run on this build?`

FYI: @liamg

**Comment by liamg** [comment]
Thanks for the report, I'll take a look at this first thing tomorrow :+1:

**Comment by liamg** [comment]
v1.3.0 is now building, should be available soon.

**Comment by vanmash** [comment]
Works. Thanks Liam @liamg
